name: Angular CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'npm'
          cache-dependency-path: appMedicFront/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./appMedicFront

      - name: Run Tests
        run: npm test
        working-directory: ./appMedicFront
